// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Note struct {
	ID        int64
	UserID    int64
	Body      string
	CreatedAt time.Time
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
}
