// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const countNotes = `-- name: CountNotes :one
SELECT COUNT(*) FROM notes
`

func (q *Queries) CountNotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByID = `-- name: CountUsersByID :one
SELECT COUNT(*) FROM users WHERE id = ?
`

func (q *Queries) CountUsersByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNote = `-- name: CreateNote :exec
INSERT INTO notes (user_id, body) VALUES (?, ?)
`

type CreateNoteParams struct {
	UserID int64
	Body   string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) error {
	_, err := q.db.ExecContext(ctx, createNote, arg.UserID, arg.Body)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (email, password_hash) VALUES (?, ?)
ON CONFLICT (email) DO NOTHING
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Email, arg.PasswordHash)
	return err
}

const notesOfUser = `-- name: NotesOfUser :many
SELECT id, user_id, body, created_at FROM notes
WHERE user_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) NotesOfUser(ctx context.Context, userID int64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, notesOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userByEmail = `-- name: UserByEmail :one

SELECT id, email, password_hash FROM users WHERE email = ?
`

// Every query of the app is here. sqlc checks each one against the
// migrations and writes its Go function: run `mise run generate` after a
// change. Scope each query on notes by the user.
func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash)
	return i, err
}
